//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчёт об оценке.
    /// </summary>
    // *** Start programmer edit section *** (ОтчётОбОценке CustomAttributes)

    // *** End programmer edit section *** (ОтчётОбОценке CustomAttributes)
    [AutoAltered()]
    [Caption("Отчёт об оценке")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчётОбОценкеE", new string[] {
            "ДатаОтчёта as \'Дата отчёта\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("ОтчётОбОценкеE", "ОценкаИнфа", "ОценкаИнфаE", true, "", "Оценка инфа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОтчётОбОценкеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОтчётОбОценкеL", new string[] {
            "ДатаОтчёта as \'Дата отчёта\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'"})]
    public class ОтчётОбОценке : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОтчёта;
        
        private IIS.Proekt2.Сотрудники fСотрудники;
        
        private IIS.Proekt2.DetailArrayOfОценкаИнфа fОценкаИнфа;
        
        // *** Start programmer edit section *** (ОтчётОбОценке CustomMembers)

        // *** End programmer edit section *** (ОтчётОбОценке CustomMembers)

        
        /// <summary>
        /// ДатаОтчёта.
        /// </summary>
        // *** Start programmer edit section *** (ОтчётОбОценке.ДатаОтчёта CustomAttributes)

        // *** End programmer edit section *** (ОтчётОбОценке.ДатаОтчёта CustomAttributes)
        public virtual System.DateTime ДатаОтчёта
        {
            get
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.ДатаОтчёта Get start)

                // *** End programmer edit section *** (ОтчётОбОценке.ДатаОтчёта Get start)
                System.DateTime result = this.fДатаОтчёта;
                // *** Start programmer edit section *** (ОтчётОбОценке.ДатаОтчёта Get end)

                // *** End programmer edit section *** (ОтчётОбОценке.ДатаОтчёта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.ДатаОтчёта Set start)

                // *** End programmer edit section *** (ОтчётОбОценке.ДатаОтчёта Set start)
                this.fДатаОтчёта = value;
                // *** Start programmer edit section *** (ОтчётОбОценке.ДатаОтчёта Set end)

                // *** End programmer edit section *** (ОтчётОбОценке.ДатаОтчёта Set end)
            }
        }
        
        /// <summary>
        /// Отчёт об оценке.
        /// </summary>
        // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники Get start)

                // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники Get start)
                IIS.Proekt2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники Get end)

                // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники Set start)

                // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтчётОбОценке.Сотрудники Set end)

                // *** End programmer edit section *** (ОтчётОбОценке.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Отчёт об оценке.
        /// </summary>
        // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаИнфа CustomAttributes)

        // *** End programmer edit section *** (ОтчётОбОценке.ОценкаИнфа CustomAttributes)
        public virtual IIS.Proekt2.DetailArrayOfОценкаИнфа ОценкаИнфа
        {
            get
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаИнфа Get start)

                // *** End programmer edit section *** (ОтчётОбОценке.ОценкаИнфа Get start)
                if ((this.fОценкаИнфа == null))
                {
                    this.fОценкаИнфа = new IIS.Proekt2.DetailArrayOfОценкаИнфа(this);
                }
                IIS.Proekt2.DetailArrayOfОценкаИнфа result = this.fОценкаИнфа;
                // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаИнфа Get end)

                // *** End programmer edit section *** (ОтчётОбОценке.ОценкаИнфа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаИнфа Set start)

                // *** End programmer edit section *** (ОтчётОбОценке.ОценкаИнфа Set start)
                this.fОценкаИнфа = value;
                // *** Start programmer edit section *** (ОтчётОбОценке.ОценкаИнфа Set end)

                // *** End programmer edit section *** (ОтчётОбОценке.ОценкаИнфа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчётОбОценкеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчётОбОценкеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчётОбОценкеE", typeof(IIS.Proekt2.ОтчётОбОценке));
                }
            }
            
            /// <summary>
            /// "ОтчётОбОценкеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчётОбОценкеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчётОбОценкеL", typeof(IIS.Proekt2.ОтчётОбОценке));
                }
            }
        }
    }
}
