//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оценка инфа.
    /// </summary>
    // *** Start programmer edit section *** (ОценкаИнфа CustomAttributes)

    // *** End programmer edit section *** (ОценкаИнфа CustomAttributes)
    [AutoAltered()]
    [Caption("Оценка инфа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОценкаИнфаE", new string[] {
            "Номер as \'Номер\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'",
            "Оценка as \'Оценка\'",
            "Оценка.ДатаПроведения as \'Дата проведения\'",
            "Оценка.Статус as \'Статус\'",
            "Оценка.Комментарий as \'Комментарий\'"}, Hidden=new string[] {
            "Сотрудники.ФИО",
            "Оценка.Комментарий"})]
    [MasterViewDefineAttribute("ОценкаИнфаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОценкаИнфаE", "Оценка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Комментарий")]
    public class ОценкаИнфа : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Proekt2.Оценка fОценка;
        
        private IIS.Proekt2.Сотрудники fСотрудники;
        
        private IIS.Proekt2.ОтчётОбОценке fОтчётОбОценке;
        
        // *** Start programmer edit section *** (ОценкаИнфа CustomMembers)

        // *** End programmer edit section *** (ОценкаИнфа CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ОценкаИнфа.Номер CustomAttributes)

        // *** End programmer edit section *** (ОценкаИнфа.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ОценкаИнфа.Номер Get start)

                // *** End programmer edit section *** (ОценкаИнфа.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ОценкаИнфа.Номер Get end)

                // *** End programmer edit section *** (ОценкаИнфа.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОценкаИнфа.Номер Set start)

                // *** End programmer edit section *** (ОценкаИнфа.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ОценкаИнфа.Номер Set end)

                // *** End programmer edit section *** (ОценкаИнфа.Номер Set end)
            }
        }
        
        /// <summary>
        /// Оценка инфа.
        /// </summary>
        // *** Start programmer edit section *** (ОценкаИнфа.Оценка CustomAttributes)

        // *** End programmer edit section *** (ОценкаИнфа.Оценка CustomAttributes)
        [PropertyStorage(new string[] {
                "Оценка"})]
        [NotNull()]
        public virtual IIS.Proekt2.Оценка Оценка
        {
            get
            {
                // *** Start programmer edit section *** (ОценкаИнфа.Оценка Get start)

                // *** End programmer edit section *** (ОценкаИнфа.Оценка Get start)
                IIS.Proekt2.Оценка result = this.fОценка;
                // *** Start programmer edit section *** (ОценкаИнфа.Оценка Get end)

                // *** End programmer edit section *** (ОценкаИнфа.Оценка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОценкаИнфа.Оценка Set start)

                // *** End programmer edit section *** (ОценкаИнфа.Оценка Set start)
                this.fОценка = value;
                // *** Start programmer edit section *** (ОценкаИнфа.Оценка Set end)

                // *** End programmer edit section *** (ОценкаИнфа.Оценка Set end)
            }
        }
        
        /// <summary>
        /// Оценка инфа.
        /// </summary>
        // *** Start programmer edit section *** (ОценкаИнфа.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОценкаИнфа.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОценкаИнфа.Сотрудники Get start)

                // *** End programmer edit section *** (ОценкаИнфа.Сотрудники Get start)
                IIS.Proekt2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОценкаИнфа.Сотрудники Get end)

                // *** End programmer edit section *** (ОценкаИнфа.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОценкаИнфа.Сотрудники Set start)

                // *** End programmer edit section *** (ОценкаИнфа.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОценкаИнфа.Сотрудники Set end)

                // *** End programmer edit section *** (ОценкаИнфа.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proekt2.ОтчётОбОценке.
        /// </summary>
        // *** Start programmer edit section *** (ОценкаИнфа.ОтчётОбОценке CustomAttributes)

        // *** End programmer edit section *** (ОценкаИнфа.ОтчётОбОценке CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ОтчётОбОценке"})]
        public virtual IIS.Proekt2.ОтчётОбОценке ОтчётОбОценке
        {
            get
            {
                // *** Start programmer edit section *** (ОценкаИнфа.ОтчётОбОценке Get start)

                // *** End programmer edit section *** (ОценкаИнфа.ОтчётОбОценке Get start)
                IIS.Proekt2.ОтчётОбОценке result = this.fОтчётОбОценке;
                // *** Start programmer edit section *** (ОценкаИнфа.ОтчётОбОценке Get end)

                // *** End programmer edit section *** (ОценкаИнфа.ОтчётОбОценке Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОценкаИнфа.ОтчётОбОценке Set start)

                // *** End programmer edit section *** (ОценкаИнфа.ОтчётОбОценке Set start)
                this.fОтчётОбОценке = value;
                // *** Start programmer edit section *** (ОценкаИнфа.ОтчётОбОценке Set end)

                // *** End programmer edit section *** (ОценкаИнфа.ОтчётОбОценке Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОценкаИнфаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОценкаИнфаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОценкаИнфаE", typeof(IIS.Proekt2.ОценкаИнфа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОценкаИнфа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОценкаИнфа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОценкаИнфа CustomAttributes)
    public class DetailArrayOfОценкаИнфа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proekt2.DetailArrayOfОценкаИнфа members)

        // *** End programmer edit section *** (IIS.Proekt2.DetailArrayOfОценкаИнфа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОценкаИнфа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОценкаИнфа.
        /// </summary>
        public DetailArrayOfОценкаИнфа(IIS.Proekt2.ОтчётОбОценке fОтчётОбОценке) : 
                base(typeof(ОценкаИнфа), ((ICSSoft.STORMNET.DataObject)(fОтчётОбОценке)))
        {
        }
        
        public IIS.Proekt2.ОценкаИнфа this[int index]
        {
            get
            {
                return ((IIS.Proekt2.ОценкаИнфа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proekt2.ОценкаИнфа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
